name: lint_hard
version: 7.0.0
homepage: https://github.com/noojee/lint_hard.git
description: All the lints except where they clash.
repository: https://github.com/noojee/lint_hard.git
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  analysis_server_plugin: ^0.3.4
dev_dependencies:
  test: ^1.25.0
