name: example
version: 0.1.1
publish_to: none
description: An example project that uses lint_hard.
environment: 
  sdk: '>=3.7.0 <4.0.0'
dev_dependencies: 
  document_throws: ^0.1.0
  lint_hard: 
    path: ..
  throws_annotations: ^0.1.0
