name: throws_annotations
version: 0.1.0
description: Provides @Throws annotations for documenting thrown exceptions.
repository: https://github.com/noojee/lint_hard.git
environment:
  sdk: '>=3.7.0 <4.0.0'
